version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./company_profile:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    # command: >
    #   sh -c "mkdir -p storage bootstrap/cache
    #         && chown -R www-data:www-data storage bootstrap/cache
    #         && chmod -R 775 storage bootstrap/cache
    #         && php-fpm"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: laravel_composer
    working_dir: /var/www
    volumes:
      - ./company_profile:/var/www
    environment:
      COMPOSER_PROCESS_TIMEOUT: 2000
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./company_profile:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
